plugins {
	id 'base'
	id 'fabric-loom' version "${loom_version}" apply false
	id 'net.fabricmc.fabric-loom' version "${loom_version}" apply false
	id 'com.gradleup.shadow' version '9.2.2' apply false
}

version = project.mod_version
group = project.maven_group

allprojects {
	version = rootProject.mod_version
	group = rootProject.maven_group
}

subprojects {
	repositories {
		mavenCentral()
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
	}
}

tasks.named('build') {
	dependsOn ':fabric-1.21.11:build'
	dependsOn ':paper-plugin:build'
	dependsOn ':paper-plugin-26.2:build'
	dependsOn ':mcng-core:build'
	dependsOn ':mcng-fabric-client:build'
}
