plugins {
	id 'fabric-loom'
	id 'maven-publish'
}

base {
	archivesName = "${project.archives_base_name}-fabric-client"
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	implementation project(':mcng-core')

	testImplementation platform('org.junit:junit-bom:5.11.4')
	testImplementation 'org.junit.jupiter:junit-jupiter'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
	useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
	options.release = 21
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			from components.java
			artifactId = "${project.archives_base_name}-fabric-client"
		}
	}
}
